import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { Hero } from "@/components/Hero";
import { Button } from "@/components/ui/button";
import { Link } from "wouter";
import { Leaf, Wind, Sun, Droplets, CheckCircle2, Award, TrendingDown } from "lucide-react";

export default function GreenEnergy() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      
      <Hero
        title="Renewable Energy For Businesses"
        description="Certified 100% renewable electricity and carbon neutral gas. Know that your electricity is 100% green, and offset your gas carbon emissions."
        primaryCTA={{ text: "Get a Quote", href: "/quote" }}
        secondaryCTA={{ text: "Learn More", href: "#benefits" }}
        badge="100% Renewable Energy"
      />

      {/* Why Choose Section */}
      <section className="py-16 lg:py-24 bg-background">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-12">
            <h2 className="text-3xl lg:text-4xl font-bold mb-4">Why Choose Green Business Energy?</h2>
            <p className="text-lg text-muted-foreground">
              Meet your sustainability goals while supporting your business growth
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="text-center" data-testid="benefit-pure-green">
              <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-4">
                <Leaf className="w-8 h-8 text-primary" />
              </div>
              <h3 className="font-semibold text-lg mb-2">100% Pure Green Electricity</h3>
              <p className="text-muted-foreground text-sm">
                Know that your business electricity is 100% clean, generated by renewable sources
              </p>
            </div>

            <div className="text-center" data-testid="benefit-rego-backed">
              <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-4">
                <Award className="w-8 h-8 text-primary" />
              </div>
              <h3 className="font-semibold text-lg mb-2">REGO Backed</h3>
              <p className="text-muted-foreground text-sm">
                Renewable Energy Guarantees of Origin certificates confirm your electricity is sourced from 100% renewable generation
              </p>
            </div>

            <div className="text-center" data-testid="benefit-zero-carbon">
              <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-4">
                <TrendingDown className="w-8 h-8 text-primary" />
              </div>
              <h3 className="font-semibold text-lg mb-2">Zero Carbon Emissions</h3>
              <p className="text-muted-foreground text-sm">
                Allows your business to report zero carbon emissions and support your CSR agenda
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Renewable Sources Section */}
      <section className="py-16 lg:py-24 bg-primary text-primary-foreground">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-12">
            <h2 className="text-3xl lg:text-4xl font-bold mb-4">REGO Backed Green Electricity Plans</h2>
            <p className="text-lg text-primary-foreground/90">
              Our Green Electricity plans are REGO-backed, meaning you can relax, knowing you're powering your business with clean, green energy.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">
            <div className="text-center" data-testid="source-wind-solar">
              <div className="w-16 h-16 rounded-full bg-white/10 backdrop-blur-sm flex items-center justify-center mx-auto mb-4">
                <Wind className="w-8 h-8 text-white" />
              </div>
              <h3 className="font-semibold text-lg mb-2">Wind & Solar</h3>
              <p className="text-sm text-primary-foreground/80">
                Green energy generated by wind turbines and solar panels
              </p>
            </div>

            <div className="text-center" data-testid="source-geothermal">
              <div className="w-16 h-16 rounded-full bg-white/10 backdrop-blur-sm flex items-center justify-center mx-auto mb-4">
                <Sun className="w-8 h-8 text-white" />
              </div>
              <h3 className="font-semibold text-lg mb-2">Geothermal & Hydrothermal</h3>
              <p className="text-sm text-primary-foreground/80">
                Renewable energy, generated within the Earth
              </p>
            </div>

            <div className="text-center" data-testid="source-biogasses">
              <div className="w-16 h-16 rounded-full bg-white/10 backdrop-blur-sm flex items-center justify-center mx-auto mb-4">
                <Droplets className="w-8 h-8 text-white" />
              </div>
              <h3 className="font-semibold text-lg mb-2">Biogasses & More</h3>
              <p className="text-sm text-primary-foreground/80">
                Sustainable energy created by a variety of green sources
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-16 lg:py-24 bg-muted/30" id="benefits">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="text-3xl lg:text-4xl font-bold mb-6">Benefits of Choosing a Sustainable Business Energy Plan</h2>
              <div className="space-y-4">
                <div className="flex items-start gap-3" data-testid="benefit-credentials">
                  <CheckCircle2 className="w-6 h-6 text-primary flex-shrink-0 mt-1" />
                  <div>
                    <h3 className="font-semibold mb-1">Renewable Credentials</h3>
                    <p className="text-sm text-muted-foreground">Show a positive commitment to sustainability and environmental responsibility.</p>
                  </div>
                </div>
                <div className="flex items-start gap-3" data-testid="benefit-fixed-plans">
                  <CheckCircle2 className="w-6 h-6 text-primary flex-shrink-0 mt-1" />
                  <div>
                    <h3 className="font-semibold mb-1">Fixed Energy Plans</h3>
                    <p className="text-sm text-muted-foreground">Available as a Fixed Energy plan for 12, 24 and 36 months.</p>
                  </div>
                </div>
                <div className="flex items-start gap-3" data-testid="benefit-verified">
                  <CheckCircle2 className="w-6 h-6 text-primary flex-shrink-0 mt-1" />
                  <div>
                    <h3 className="font-semibold mb-1">Verified Schemes</h3>
                    <p className="text-sm text-muted-foreground">Backed by verified sustainability schemes, including the OFGEM administered REGO scheme, and Verra.</p>
                  </div>
                </div>
                <div className="flex items-start gap-3" data-testid="benefit-csr">
                  <CheckCircle2 className="w-6 h-6 text-primary flex-shrink-0 mt-1" />
                  <div>
                    <h3 className="font-semibold mb-1">CSR Goals</h3>
                    <p className="text-sm text-muted-foreground">Help meet your corporate social responsibility goals and demonstrate environmental leadership.</p>
                  </div>
                </div>
              </div>
            </div>
            <div className="bg-card p-8 lg:p-12 rounded-lg border border-card-border">
              <h3 className="text-2xl font-bold mb-4">Greener Gas Options</h3>
              <p className="mb-6 text-muted-foreground">
                We work with our trusted partners to offset gas carbon emissions through their Verified Carbon Standard (VCS) Program. This popular program helps reduce greenhouse gas emissions, which are harmful to the environment.
              </p>
              <p className="mb-6 text-muted-foreground">
                Sometimes it's not possible for businesses to completely stop their emissions right away. By taking out a carbon offset renewable business energy plan, businesses can invest in environmental projects that reduce carbon elsewhere.
              </p>
              <Link href="/quote">
                <Button size="lg" className="w-full bg-primary hover:bg-primary text-primary-foreground" data-testid="button-green-quote">
                  Get a Green Energy Quote
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 lg:py-20 bg-secondary text-secondary-foreground">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl mx-auto text-center">
            <h2 className="text-3xl lg:text-4xl font-bold mb-6">
              Ready to Power Your Business Sustainably?
            </h2>
            <p className="text-lg text-secondary-foreground/80 mb-8">
              Get a quote for 100% renewable electricity and carbon neutral gas today
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a href="tel:03333233940" data-testid="button-call-green">
                <Button size="lg" className="bg-accent hover:bg-accent text-accent-foreground">
                  Call 0333 323 3940
                </Button>
              </a>
              <Link href="/quote">
                <Button size="lg" variant="outline" className="border-secondary-foreground/20 hover:bg-secondary-foreground/5" data-testid="button-quote-green">
                  Get a Quote Online
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
